### ISSUE TITLE
#egg=my-package==1.2 does not extract specs

### ISSUE THREAD

**Issue by stefanfoulis** [madpah/requirements-parser#21]
For cases where the `#egg` tag also includes the version, the version is not split from the name correctly.

`http://my-server.com/packages/my-package-1.2.tar.gz#egg=my-package==1.2` results:
- `requirement.name`: `my-package==1.2`
- `requirement.specs`: `[]`

Shouldn't it be like this?:
- `requirement.name`: `my-package`
- `requirement.specs`: `[('==', '1.2')]`

This is probably also the case for VCS and LOCAL.

**Comment by davidfischer** [comment]
Are those valid `#egg` specifiers? I don't see any examples like that in the [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format).

**Comment by jonrkarr** [comment]
This is a great package. Unfortunately, extras are also not parsed correctly when the `#egg` tag is used with non-PyPI packages.

For example, `git+https://github.com/org/package.git#egg=package [option]`

Produces `name=package [option]` and `extras=[]` when it should be `name=package` and `extras=[option]`

**Comment by madpah** [comment]
Given [PyPi has noted Egg distribution](https://blog.pypi.org/posts/2023-06-26-deprecate-egg-uploads/) upload is deprecated as of 26 June 2023, I'm going to close this as no longer relevant.

Please re-open if you disagree @stefanfoulis.
