### ISSUE TITLE
This project is actively seeking maintainers

### ISSUE THREAD

**Issue by jhermann** [madpah/requirements-parser#45]
:bulb: A move to https://github.com/jazzband might lighten the load.

**Comment by davidfischer** [comment]
I'm not sure anyone is super actively using this project. If the jazzband folks want to take it over, I'd be fine transferring it.

**Comment by jhermann** [comment]
I found these possible alternatives:

* https://github.com/toxinu/requirements (2016)
* https://github.com/sarugaku/requirementslib (current)
* https://github.com/requirements/rparse (2015)

If you find the time, maybe you can take a look (at the requirementslib one)  and judge on how they compare to your code / features and add a recommendation to the README.

**Comment by domdfcoding** [comment]
Just came across this project and it fits my needs perfectly (requirementslib looks overkill).

Happy to help with maintenance when required.

**Comment by kousu** [comment]
requirementslib also doesn't actually parse requirements.txt files. The closest I got was:

```
>>> [requirementslib.Requirement.from_line(l) for l in open("requirements.txt")]
```

but that crashes on, for example, comments:

```
pip._internal.exceptions.InstallationError: Invalid requirement: 'numpy  # the venerable numerical package'
```

**Comment by jgarte** [comment]
I'd be happy to help with maintenance of this package also. I could use it for a project I'm currently working on that needs to parse a requirements.txt file.

**Comment by davidfischer** [comment]
I transferred the project to @madpah who is taking on maintenance. Hopefully the project continues well and feel free to collaborate.
