### ISSUE TITLE
Can you publish a universal (2 & 3) wheel?

### ISSUE THREAD

**Issue by matthewdeanmartin** [madpah/requirements-parser#55]
Usually you get a universal wheel by default, [this set of files as of now is only a python 2 wheel](https://pypi.org/project/requirements-parser/#files).

`python setup.py bdist_wheel`

This question suggests that if you aren't getting an universal wheel to try

`python3 setup.py bdist_wheel --universal`
https://stackoverflow.com/a/30438777/33264 

Anyhow, some upstream projects that would prefer to use wheels as a supply chain security mitigation would much appreciate it.

Matthew Martin

**Comment by madpah** [comment]
@matthewdeanmartin - a Python 3 wheel has now been published as of `0.3.0`.

Python 2 support has been deprecated it is now EOL (https://www.python.org/downloads/).

**Comment by matthewdeanmartin** [comment]
Perfect, thanks!
