### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by pombredanne** [madpah/requirements-parser#57]
I was wondering about the basis for the license change at https://github.com/madpah/requirements-parser/pull/56/commits/5b7a6e49e355a37fa6674876db4b692e8bf82943 ... this is not problematic, but I could not find any issue or discussion with @davidfischer on the topic.

Thanks!

**Comment by davidfischer** [comment]
I'm fine with the license change as I'm pretty much done with the project. However, I don't know the reasons behind the license change. I basically never use the Apache license but if the new maintainers want to change the license for future versions, that's up to them.

**Comment by pombredanne** [comment]
@davidfischer Thanks for the clarification!

**Comment by madpah** [comment]
@pombredanne - apologies - was really just boiler plate to keep in line with other projects I maintain.

If there's a (legal) objection, do let me know, else I'll close this.

Thanks!

**Comment by pombredanne** [comment]
> If there's a (legal) objection, do let me know, else I'll close this.

No objection at all...things were not completely clear to me hence why I had brought this up.
My only comment is that there are a few other contributors and it may be cool to ask them too?

FWIW, I have been using dparse so far for parsing requirements in scancode https://github.com/nexB/scancode-toolkit/blob/9ed2cb4e78a8b1b138bcb201f50203b43098febb/src/packagedcode/pypi.py#L750
But dparse is not super actively maintained so much so that I forked it https://github.com/nexB/dparse
Therefore, I am considering your library instead!
Licensing being rather central to scancode, I tend to be rather conservative there, especially when there are license changes. 
Thanks to both of you!

**Comment by madpah** [comment]
Thanks for the insight @pombredanne. Always keen for input and opinions!
