### ISSUE TITLE
Library relies on deprecated pkg_resources

### ISSUE THREAD

**Issue by gotmax23** [madpah/requirements-parser#88]
This package imports pkg_resources

https://github.com/madpah/requirements-parser/blob/1ce923617147dd984c280d56cb1f02fcd3589a7c/requirements/requirement.py#L24

which is deprecated. Simply importing the package raises a DeprecationWarning. The library should migrate to `packaging.requirements.Requirement` instead of `pkg_resources.Requirement`.

**Comment by felixfontein** [comment]
This is failing on Python 3.12: https://github.com/ansible-collections/community.docker/actions/runs/7513305230/job/20454910945?pr=754

**Comment by gotmax23** [comment]
> This is failing on Python 3.12: https://github.com/ansible-collections/community.docker/actions/runs/7513305230/job/20454910945?pr=754

That is because the package is missing an explicit dependency on setuptools, but it looks like that was fixed on main.
